project:
  title: "article"
  render:
    - article.qmd
format:
  pdf:
    colorlinks: true
    pdf-engine: tectonic
    fig-pos: "H"
    documentclass: scrartcl
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    include-in-header:
      - header.tex
title: |
  \Large

  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
subtitle: "Article"
author: "Author"
abstract: |
  \vspace{-1.5cm}
  \singlespacing
  \zeroIndent

  \nid \lipsum[1]

  \vspace{0.5cm}

  **Keywords**: Lorem, Ipsum.
fontsize: 12pt
bibliography: references.bib
csl: abnt.csl
nocite: "@*"
lang: en-US
link-citations: yes
cap-location: top
