project:
  title: "article"
  render:
    - article.qmd
format:
  pdf:
    colorlinks: true
    documentclass: scrartcl
    fig-pos: "H"
    link-citations: true
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    include-in-header:
      - ./aux_files/headers/packages.tex
      - ./aux_files/headers/commands.tex
      - ./aux_files/headers/settings.tex
title: \Large Lorem ipsum dolor sit amet
subtitle: "Article"
author: "Author"
abstract: |
  \vspace{-1.5cm}
  \singlespacing
  \zeroIndent

  \nid \lipsum[1]

  \vspace{0.5cm}

  **Keywords**: Lorem, Ipsum.
fontsize: 12pt
bibliography: ./aux_files/references.bib
csl: ./aux_files/abnt.csl
nocite: "@*"
lang: en-US
cap-location: top
