title: "Title"
subtitle: "Subtitle"
author: "Author"
format:
  revealjs:
    theme: simple
    footer: "Footer text"
    slide-number: c/t
    progress: true
    transition: slide
    slide-level: 1
fontsize: 20pt
reference-section-title: References
lang: pt-BR
nocite: "@*"
bibliography: references.bib
