---
output:   
  pdf_document:
    fig_caption: yes
    number_sections: yes
bibliography: referencias.bib
csl: abnt.csl
fontsize: 12pt
geometry:
- top=2.5cm
- bottom=2.5cm
- left=2.5cm
- right=2.5cm
header-includes:
- \usepackage{setspace}
- \usepackage{ragged2e}
- \usepackage{indentfirst}
- \usepackage{fancyhdr}
- \usepackage{microtype}
- \usepackage{chngcntr}
- \usepackage{booktabs}
- \usepackage{graphicx}
- \usepackage[justification = centering, tableposition = top, font = small]{caption}
- \usepackage[position = top]{subfig}
- \usepackage{float}
- \usepackage{multirow}
- \usepackage{lipsum}
- \captionsetup[subfigure]{font = scriptsize, labelfont = scriptsize}
indent: no
reference-section-title: Referências
nocite: null
lang: pt-BR
link-citations: yes
---
<!--- Lista contínua de tabelas e imagens --->

```{=tex}
\counterwithin{figure}{section}
\counterwithin{table}{section}
```

<!-- Remover tudo menos os resultados dos chunks --->

```{r, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE, error=FALSE, warning=FALSE, message=FALSE)
```

<!-- Parágrafos e espaçamento --->

```{=tex}
\setlength{\parindent}{1.25cm}
\setlength{\parskip}{0.1cm}
\onehalfspacing
\justifying
\pagenumbering{gobble}
```

<!-- Capa --->

```{r child = 'capa.Rmd'}
```

<!-- Resumo --->

```{r child = '0_resumo.Rmd'}
```

<!--- Lista de figuras --->

```{=tex}
\listoffigures
\newpage
```

<!--- Lista de tabelas --->

```{=tex}
\listoftables
\newpage
```

<!-- Sumário -->

```{=tex}
\tableofcontents
\newpage
```

<!-- Cabeçalhos - Geral -->
```{=tex}
\pagestyle{fancy}
\setlength\headheight{15pt}
\fancyhead[L]{}
\fancyhead[R]{}
```

# Introdução

```{=tex}
\pagenumbering{arabic}
```

<!--- Cabeçalho--->

```{=tex}
\thispagestyle{plain}
\pagenumbering{arabic}
\fancyhead[C]{Introdução}
```

```{r child = '1_introducao.Rmd'}
```

# Desenvolvimento

<!--- Cabeçalho--->

```{=tex}
\thispagestyle{plain}
\fancyhead[C]{Desenvolvimento}
```

```{r child = '2_desenvolvimento.Rmd'}
```

# Conclusão {-}

<!--- Cabeçalho--->
```{=tex}
\thispagestyle{plain}
\fancyhead[C]{Conclusão}
```

```{r child = '3_conclusao.Rmd'}
```

<!-- Parágrafos e espaçamento (referências) --->

```{=tex}
\pagestyle{plain}
\small
\singlespacing
\setlength{\parindent}{0cm}
```
