---
format: 
  pdf:
    number-sections: true
    colorlinks: true
    fig-pos: "h"
    include-in-header:
      - header.tex
bibliography: references.bib
csl: abnt.csl
fontsize: 12pt
geometry:
  - top=3cm
  - bottom=2cm
  - left=3cm
  - right=2cm
indent: no
reference-section-title: Referências
nocite: null
lang: pt-BR
link-citations: yes
cap-location: top
---

<!--- cover --->

```{r child = 'pre_sections/01_cover.qmd'}
```

<!--- catalographic index --->

```{r child = 'pre_sections/02_cover_catalographic_index.qmd'}
```

<!--- signatures --->

```{r child = 'pre_sections/03_signatures.qmd'}
```

<!--- thanks --->

```{r child = 'pre_sections/04_thanks.qmd'}
```

<!--- abstract --->

```{r child = 'pre_sections/05_abstract_pt.qmd'}
```

```{r child = 'pre_sections/06_abstract_en.qmd'}
```

<!--- list of figures --->

```{=tex}
\listoffigures
\jumpTwoPages
```

<!--- list of tables --->

```{=tex}
\listoftables
\jumpTwoPages
```

<!--- table of contents --->

```{=tex}
\tableofcontents
\jumpTwoPages
```

# Introdução {-}

```{=tex}
\pagenumbering{arabic}
\header{Introdução}
```

```{r child = '1_introduction.qmd'}
```

# Desenvolvimento 

```{=tex}
\header{Desenvolvimento}
```

```{r child = '2_main_body.qmd'}
```

# Conclusão {-}

```{=tex}
\header{Conclusão}
```

```{r child = '3_conclusion.qmd'}
```

<!--- references --->

```{=tex}
\referenceStyle
```
