project:
  title: "article"
  preview:
    port: 4200
  render:
    - thesis.qmd
format:
  pdf:
    number-sections: true
    colorlinks: true
    fig-pos: "H"
    link-citations: true
    include-in-header:
      - ./aux_files/headers/packages.tex
      - ./aux_files/headers/commands.tex
      - ./aux_files/headers/settings.tex
bibliography: ./aux_files/references.bib
csl: ./aux_files/abnt.csl
fontsize: 12pt
geometry:
  - top=3cm
  - bottom=2cm
  - left=3cm
  - right=2cm
indent: false
nocite: "@*"
lang: pt-BR
cap-location: top
